---

- hosts: localhost 
  connection: local

  tasks:

  - name: Make sure we have pip
    become: true
    yum: pkg=python-pip state=latest
            
  - name: Install Python modules
    become: true
    pip: name={{ item }} state=latest
    with_items:
        - pysphere
        - pyvmomi
         
# Remove a vm from vCenter
# All VM's must be powered off 

  - vsphere_guest:
        validate_certs: false
        vcenter_hostname: 10.1.183.5
        username: root
        password: vmware
        guest: "{{ item }}"
        state: absent 
        force: yes
    with_items:
       - vm_5702
       - vm_27694
       - vm_19440
    tags:
       - delete_vms

# Deploy a guest from a template
  - vsphere_guest:
        validate_certs: false
        vcenter_hostname: 10.1.183.5 
        username: root 
        password: vmware 
        esxi: 
            datacenter: CECS-POD3 
            hostname: 10.1.183.7
        guest: newvm-david
        from_template: yes
        template_src: workercliqr
        cluster: CECS
        vm_extra_config:
            folder: CliqrDeployedVMs 
    tags:
        - deploy_vm
